[[headers]]
  for = "/sw.js"
  [headers.values]
    cache-control = "max-age=0,no-cache,no-store,must-revalidate"

[[redirects]]
  from = "/techforbetter"
  to = "/tech-for-better"
  status = 301

[[redirects]]
  from = "/apprenticeship-policies/complaints.pdf"
  to = "/assets/media/EN-2A_ComplaintsPolicy_FoundersandCoders.pdf"
  status = 302