backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)

media_folder: "assets/media" # Media files will be stored in the repo under images/uploads

site_url: "https://fac-eleventy.netlify.com"

# Each page is a separate file with it's own custom fields
collections:
  - label: "Pages"
    name: "pages"
    files:
      - label: "Home Page"
        name: "home"
        file: "home/home.json"
        fields:
          - { label: Title, name: title, widget: string }
          - { label: Video, name: video, widget: file }
          - label: "Intro section"
            name: "intro"
            widget: "object"
            fields:
              - { label: Title, name: title, widget: string }
              - { label: Body, name: body, widget: markdown }
          - label: "Coop section"
            name: "coop"
            widget: "object"
            fields:
              - { label: Title, name: title, widget: string }
              - label: "Coop logos"
                name: "logos"
                widget: "list"
                field: { label: Logo, name: logo, widget: image }
          - label: "Testimonials"
            name: "testimonials"
            widget: "list"
            fields:
              - { label: Name, name: name, widget: string }
              - { label: Cohort, name: cohort, widget: string }
              - { label: Quote, name: quote, widget: string }
              - { label: Image, name: image, widget: image }
      - label: "About Page"
        name: "about"
        file: "about/about.json"
        fields:
          - { label: Title, name: title, widget: string }
          - { label: Intro, name: intro, widget: markdown }
          - label: "FAQ Section"
            name: "faqSection"
            widget: "object"
            fields:
              - { label: Title, name: title, widget: string }
              - label: "FAQs"
                name: "faqs"
                widget: "list"
                fields:
                  - { label: Title, name: title, widget: string }
                  - { label: Body, name: body, widget: markdown }
              - { label: Outro, name: outro, widget: markdown }
          - label: "Team section"
            name: "teamSection"
            widget: "object"
            fields:
              - { label: Title, name: title, widget: string }
              - { label: Intro, name: intro, widget: markdown }
              - label: "team"
                name: "team"
                widget: "list"
                fields:
                  - { label: Name, name: name, widget: string }
                  - { label: Cohort, name: cohort, widget: string }
                  - { label: Quote, name: quote, widget: string }
                  - { label: Image, name: image, widget: image }
      - label: "Apply Page"
        name: "apply"
        file: "apply/apply.json"
        fields:
          - { label: Title, name: title, widget: string }
          - { label: Intro, name: intro, widget: markdown }
          - label: "Cohort Section"
            name: "cohortSection"
            widget: "object"
            fields:
              - { label: Title, name: title, widget: string }
              - label: "Cohorts"
                name: "cohorts"
                widget: "list"
                fields:
                  - { label: Name, name: name, widget: string }
                  - label: "Dates"
                    name: "dates"
                    widget: "list"
                    fields:
                      - { label: Title, name: title, widget: string }
                      - { label: Open date, name: open, widget: date }
                      - { label: Close date, name: close, widget: date }
          - label: "Apply Section"
            name: "apply"
            widget: "object"
            fields:
              - { label: Title, name: title, widget: string }
              - label: "Steps"
                name: "steps"
                widget: "list"
                fields:
                  - { label: Title, name: title, widget: string }
                  - { label: Body, name: body, widget: markdown }
          - label: "Prereqs Section"
            name: "prereqs"
            widget: "object"
            fields:
              - { label: Title, name: title, widget: string }
              - { label: Body, name: body, widget: markdown }
      - label: "Hire Page"
        name: "hire"
        file: "hire/hire.json"
        fields:
          - { label: Title, name: title, widget: string }
          - { label: Intro, name: intro, widget: markdown }
          - { label: Image, name: image, widget: image }
          - label: "Partner logos"
            name: "partners"
            widget: "list"
            field: { label: Logo, name: logo, widget: image }
