backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)

media_folder: "assets/media" # Media files will be stored in the repo under images/uploads

# Each page is a separate file with it's own custom fields
collections:
  - label: "Pages"
    name: "pages"
    files:
      - label: "Home Page"
        name: "home"
        file: "home/home.json"
        fields:
          - { label: Title, name: title, widget: string }
          - { label: Video, name: video, widget: file }
          - label: "Intro section"
            name: "intro"
            widget: "object"
            fields:
              - { label: Title, name: title, widget: text }
              - { label: Body, name: body, widget: markdown }
          - label: "Coop section"
            name: "coop"
            widget: "object"
            fields:
              - { label: Title, name: title, widget: text }
              - label: "Coop logos"
                name: "logos"
                widget: "list"
                field: { label: Logo, name: logo, widget: image }
          - label: "Testimonials"
            name: "testimonials"
            widget: "list"
            fields:
              - { label: Name, name: name, widget: string }
              - { label: Cohort, name: cohort, widget: string }
              - { label: Quote, name: quote, widget: string }
              - { label: Image, name: image, widget: image }
      #     - label: Team
      #       name: team
      #       widget: list
      #       fields:
      #         - {label: Name, name: name, widget: string}
      #         - {label: Position, name: position, widget: string}
      #         - {label: Photo, name: photo, widget: image}
      # - label: "Locations Page"
      #   name: "locations"
      #   file: "site/content/locations.yml"
      #   fields:
      #     - {label: Title, name: title, widget: string}
      #     - {label: Intro, name: intro, widget: markdown}
      #     - label: Locations
      #       name: locations
      #       widget: list
      #       fields:
      #         - {label: Name, name: name, widget: string}
      #         - {label: Address, name: address, widget: string}
