backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)

media_folder: "assets/media" # Media files will be stored in the repo under images/uploads

site_url: "https://fac-rebuild.netlify.com"

# Each page is a separate file with it's own custom fields
collections:
  - label: "Pages"
    name: "pages"
    files:
      - label: "Home Page"
        name: "home"
        file: "pages/marketing/home/home.json"
        fields:
          - { label: Title, name: title, widget: string }
          - { label: Video, name: video, widget: file }
          - label: "Intro section"
            name: "intro"
            widget: "object"
            fields:
              - { label: Title, name: title, widget: string }
              - { label: Body, name: body, widget: markdown }
          - label: "Coop section"
            name: "coop"
            widget: "object"
            fields:
              - { label: Title, name: title, widget: string }
              - label: "Coop logos"
                name: "logos"
                widget: "list"
                field: { label: Logo, name: logo, widget: image }
          - label: "Testimonials"
            name: "testimonials"
            widget: "list"
            fields:
              - { label: Name, name: name, widget: string }
              - { label: Cohort, name: cohort, widget: string }
              - { label: Quote, name: quote, widget: string }
              - { label: Image, name: image, widget: image }
      - label: "About Page"
        name: "about"
        file: "pages/marketing/about/about.json"
        fields:
          - { label: Title, name: title, widget: string }
          - { label: Intro, name: intro, widget: markdown }
          - label: "FAQ Section"
            name: "faqSection"
            widget: "object"
            fields:
              - { label: Title, name: title, widget: string }
              - label: "FAQs"
                name: "faqs"
                widget: "list"
                fields:
                  - { label: Title, name: title, widget: string }
                  - { label: Body, name: body, widget: markdown }
              - { label: Outro, name: outro, widget: markdown }
          - label: "Team section"
            name: "teamSection"
            widget: "object"
            fields:
              - { label: Title, name: title, widget: string }
              - { label: Intro, name: intro, widget: markdown }
              - label: "team"
                name: "team"
                widget: "list"
                fields:
                  - { label: Name, name: name, widget: string }
                  - { label: Cohort, name: cohort, widget: string }
                  - { label: Quote, name: quote, widget: string }
                  - { label: Image, name: image, widget: image }
      - label: "Apply Page"
        name: "apply"
        file: "pages/marketing/apply/apply.json"
        fields:
          - { label: Title, name: title, widget: string }
          - { label: Intro, name: intro, widget: markdown }
          - label: "Cohort Section"
            name: "cohortSection"
            widget: "object"
            fields:
              - { label: Title, name: title, widget: string }
              - label: "Cohorts"
                name: "cohorts"
                widget: "list"
                fields:
                  - { label: Name, name: name, widget: string }
                  - label: "Dates"
                    name: "dates"
                    widget: "list"
                    fields:
                      - { label: Title, name: title, widget: string }
                      - { label: Open date, name: open, widget: date }
                      - { label: Close date, name: close, widget: date }
          - label: "Apply Section"
            name: "apply"
            widget: "object"
            fields:
              - { label: Title, name: title, widget: string }
              - label: "Steps"
                name: "steps"
                widget: "list"
                fields:
                  - { label: Title, name: title, widget: string }
                  - { label: Body, name: body, widget: markdown }
          - label: "Prereqs Section"
            name: "prereqs"
            widget: "object"
            fields:
              - { label: Title, name: title, widget: string }
              - { label: Body, name: body, widget: markdown }
          - label: "Cohort Images Section"
            name: "cohortImageSection"
            widget: "object"
            fields:
              - { label: Title, name: title, widget: string }
              - label: "Cohort Images"
                name: "images"
                widget: "list"
                field: { label: Image, name: image, widget: image }
      - label: "Hire Page"
        name: "hire"
        file: "pages/marketing/hire/hire.json"
        fields:
          - { label: Title, name: title, widget: string }
          - { label: Intro, name: intro, widget: markdown }
          - { label: Image, name: image, widget: image }
          - label: "Quotes"
            name: "quotes"
            widget: "list"
            fields:
              - { label: Name, name: name, widget: string }
              - { label: Company, name: company, widget: string }
              - { label: Body, name: body, widget: string }
          - label: "Partner logos"
            name: "partners"
            widget: "list"
            field: { label: Logo, name: logo, widget: image }
      - label: "T4B Page"
        name: "t4b"
        file: "pages/marketing/t4b/t4b.json"
        fields:
          - { label: Title, name: title, widget: string }
          - { label: Intro, name: intro, widget: markdown }
          - { label: Image, name: image, widget: image }
          - label: "Apply Section"
            name: "apply"
            widget: "object"
            fields:
              - { label: Title, name: title, widget: string }
              - label: "Steps"
                name: "steps"
                widget: "list"
                fields:
                  - { label: Title, name: title, widget: string }
                  - { label: Body, name: body, widget: markdown }
              - label: "FAQ Section"
                name: "faqSection"
                widget: "object"
                fields:
                  - { label: Title, name: title, widget: string }
                  - label: "FAQs"
                    name: "faqs"
                    widget: "list"
                    fields:
                      - { label: Title, name: title, widget: string }
                      - { label: Body, name: body, widget: markdown }
          - label: "Case Studies"
            name: "caseStudies"
            widget: "object"
            fields:
              - { label: Title, name: title, widget: string }
              - label: "Apps"
                name: "apps"
                widget: "list"
                fields:
                  - { label: Title, name: title, widget: string }
                  - { label: Body, name: body, widget: markdown }
                  - { label: URL, name: url, widget: string }
      - label: "Hire Page"
        name: "hire"
        file: "pages/marketing/hire/hire.json"
        fields:
          - { label: Title, name: title, widget: string }
          - { label: Intro, name: intro, widget: markdown }
          - { label: Image, name: image, widget: image }
          - label: "Partner logos"
            name: "partners"
            widget: "list"
            field: { label: Logo, name: logo, widget: image }
      - label: "Events Page"
        name: "events"
        file: "pages/marketing/events/events.json"
        fields:
          - { label: Title, name: title, widget: string }
          - { label: Intro, name: intro, widget: markdown }
          - label: "Scheduled Events"
            name: "schedule"
            widget: "list"
            fields:
              - { label: Date, name: date, widget: date }
              - label: "Type"
                name: "type"
                widget: "select"
                options:
                  - {
                      label: "Coding For Everyone",
                      value: "coding-for-everyone",
                    }
                  - { label: "Short Course", value: "short-course" }
  - label: "Events"
    name: "events"
    folder: "events"
    create: true
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }
