name: CI

on: 
  schedule:
    - cron:  '25 19 * * *'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Deploy site
      run: curl -X POST -d {} https://api.netlify.com/build_hooks/5e4c30935045b417ee413d7a
